version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha_topfrango
      MYSQL_DATABASE: topfrango_db
    ports:
      - "3306:3306"

  backend:
    build: ./Servidor  
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./sistema-pdv 
    ports:
      - "3000:3000"
    stdin_open: true # Necessário para o React não fechar no Docker
    depends_on:
      - backend